name: Convert Adblock Rules to SmartDNS Format
on: [push, workflow_dispatch]
jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Download Adblock Rules
      run: curl -s https://raw.githubusercontent.com/8680/GOODBYEADS/master/rules.txt -o rules.txt
    - name: Convert to SmartDNS format
      run: |
        cat rules.txt | \
        grep "^\|\|" | \
        sed "s/^\|\|//" | \
        sed "s/\^$/#/" | \
        sed "s/|/\|/g" | \
        awk '{print "address /"\$0"#"}' \
        > smartdns-rules.conf

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add smartdns-rules.conf
        git diff --staged --quiet || (git commit -m "Convert adblock rules to SmartDNS" && git push)
