name: Update .conf file and push to repository
on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  workflow_dispatch: 
jobs:
  update_conf:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Fetch .conf file
      run: curl https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf -o domains.conf
    - name: Transform .conf content
      run: sed -n 's#server=/\(.*\)/114.114.114.114#\1#p' domains.conf > chinalist.conf
    - name: Push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add domains.conf chinalist.conf
        git diff-index --quiet HEAD || git commit -m "Update .conf file"
        git push

